# Generated by Django 5.2.17 on 2026-09-16 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0002_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingressos.setor')),
            ],
        ),
    ]
