# Generated by Django 5.2.17 on 2026-09-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0004_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='biometria_verificada',
            field=models.BooleanField(default=False),
        ),
    ]
