# Generated by Django 5.2.17 on 2026-09-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0005_pedido_biometria_verificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
