# Generated by Django 5.2.17 on 2026-09-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0006_alter_jogo_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('credito', 'Cartão de crédito'), ('debito', 'Cartão de débito')], max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20),
        ),
    ]
