# Generated by Django 5.2.17 on 2026-09-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0007_pedido_forma_pagamento_pedido_status_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ['data', 'horario']},
        ),
    ]
